apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memcore-web-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hewenze11/memcore-web.git
    targetRevision: dev
    path: k8s/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-memcore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
